### ISSUE TITLE
[New PE] Divergent partial evaluation

### ISSUE THREAD

**Issue by madmann91** [AnyDSL/thorin#82]
Compile with `-emit-thorin -Othorin`.

```rust
struct SmallStack {
    write: fn (int, float) -> (),
    read:  fn (int) -> float
}

fn @(true) make_small_stack(n: int) -> SmallStack {
    fn @(?begin & ?end) make_small_stack_helper(begin: int, end: int) -> SmallStack {
        if begin == end {
            SmallStack {
                write: @(true) |_, _| (),
                read:  @(true) |_| 0.0f
            }
        } else if begin + 1 == end {
            let mut val : float;
            SmallStack {
                write: @(true) |i, v| val = v,
                read:  @(true) |i| val
            }
        } else {
            let m = (begin + end) / 2;
            let left  = make_small_stack_helper(begin, m);
            let right = make_small_stack_helper(m, end);
            SmallStack {
                write: @(true) |i, v| if i < m { left.write(i, v) } else { right.write(i, v) },
                read:  @(true) |i|    if i < m { left.read(i)     } else { right.read(i)     }
            }
        }
    }

    make_small_stack_helper(0, n)
}

fn @(?a & ?b) range_step(a: int, b: int, @(true) c: int, @(true) body: fn (int) -> ()) -> () {
    if a < b {
        body(a);
        range_step(a + c, b, c, body, return)
    }
}

fn @(true) range(a: int, b: int, body: fn (int) -> ()) -> () {
    range_step(a, b, 1, body);
}

fn main(res: &mut [float]) -> () {
    for n in range(0, 8) {
        let tmp = make_small_stack(n);
        for i in range(0, n) {
            tmp.write(i, i as float * 42.0f);
        }
        let mut sum = 0.0f;
        for i in range(0, n) {
            let v = tmp.read(i);
            sum += v as float;
        }
        res(n) = sum;
    }
}
```

**Comment by madmann91** [comment]
As a side note, this pattern is currently the only way to get compile-time sized arrays in Impala. This might be a bit contrived, but it generates pretty efficient code since every element in the array is mapped to one alloca, and both our mem2reg and LLVM's mem2reg are able to take care of this.

**Comment by madmann91** [comment]
Besides, replacing the outer `for` loop in `main()` by `let n = <some constant>` makes the code compile.

**Comment by leissa** [comment]
This is actually a limitation of the current approach. We'll need the annotation at the call site, too:
```Rust
fn @(?a & ?b) range_step(a: int, b: int, @(true) c: int, @(true) body: fn (int) -> ()) -> () {
    if a < b {
        @body(a);
        range_step(a + c, b, c, body, return)
    }
}
```
Otherwise, the constant isn't propagated to the inner loop.

**Comment by madmann91** [comment]
But why does it work with a constant `n`, then?

**Comment by leissa** [comment]
Because then the inner loop knows the constant.

**Comment by madmann91** [comment]
Yes, but still, the other two for loops also require inlining of `tmp.write()` or `tmp.read()`. Otherwise, the value that is written into sum is not known. Yet, this seems to work _without_ any call site intervention. Is it just luck?

**Comment by leissa** [comment]
But those function expressions are annotated with `@(true)`, no?

**Comment by leissa** [comment]
Btw actually after PE the value of `sum` isn't known, only after applying `mem2reg` the value will be known. This is another limitation. But this one holds for current master just as well. We would either need to do `mem2reg` on the fly or perform loads and stores during PE in order to deal with that.

See https://github.com/AnyDSL/thorin/projects/1#card-2146514

**Comment by madmann91** [comment]
> But those function expressions are annotated with @(true), no?

Well that still does not explain it, because if you replace the outer for loop by

```rust
range(0, 8, @(true) |n| {
    let tmp = make_small_stack(n);
    /* ... */
});
```

This example still does not work.

**Comment by leissa** [comment]
This is yet a different problem, I'm currently working on :)

**Comment by madmann91** [comment]
This is now fixed with your recent changes (I just tested it)!

**Comment by madmann91** [comment]
It only worked with `range(0, 2, @ |n| /*...*/)`, but not for something bigger than 2, e.g. `range(0, 3, @ |n| /*...*/)`. My bad.

**Comment by leissa** [comment]
```Rust
struct SmallStack {
    write: fn (int, float) -> (),
    read:  fn (int) -> float
}

fn @(true) make_small_stack(n: int) -> SmallStack {
    fn @(?begin & ?end) make_small_stack_helper(begin: int, end: int) -> SmallStack {
        if begin == end {
            SmallStack {
                write: @(true) |_, _| (),
                read:  @(true) |_| 0.0f
            }
        } else if begin + 1 == end {
            let mut val : float;
            SmallStack {
                write: @(true) |i, v| val = v,
                read:  @(true) |i| val
            }
        } else {
            let m = (begin + end) / 2;
            let left  = make_small_stack_helper(begin, m);
            let right = make_small_stack_helper(m, end);
            SmallStack {
                write: @(true) |i, v| if i < m { left.write(i, v) } else { right.write(i, v) },
                read:  @(true) |i|    if i < m { left.read(i)     } else { right.read(i)     }
            }
        }
    }

    make_small_stack_helper(0, n)
}

fn @(?a & ?b) range_step(a: int, b: int, @(true) c: int, @(true) body: fn (int) -> ()) -> () {
    if a < b {
        body(a);
        range_step(a + c, b, c, body, return)
    }
}

fn @(true) range(a: int, b: int, body: fn (int) -> ()) -> () {
    range_step(a, b, 1, body);
}

fn main(res: &mut [float]) -> () {
    range(0, 8, @(true) |n| {
        let tmp = make_small_stack(n);
        range(0, n, @|i| {
            tmp.write(i, i as float * 42.0f);
        });
        let mut sum = 0.0f;
        range(0, n, @|i| {
            let v = tmp.read(i);
            sum += v as float;
        });
        res(n) = sum;
    });
}
```
With my latest change, this works now. I'll keep this issue opened until I have implemented the `@call(...)` feature.

**Comment by madmann91** [comment]
Note that it starts to be non-evaluated for `n = 5`. Everything is OK for `n = 0` ... `n = 4`.

**Comment by leissa** [comment]
Works here, even for 'n = 32'. Are you sure, you are using my variant where the inner loops also use this
```
range(0, n, @|i| { /*...*/ });
´´´
workaround?

That our mem2reg doesn't remove these slots is a missing feature, as we don't consider `lea`s at the moment. But LLVM saves us in this case.

**Comment by madmann91** [comment]
Yes, I am using the your variant, with the new syntax `for n in range(0, 4) @{ /* ... */ }`, which is equivalent (see my commits in Impala). The problem is not the slots, they are fine. The problem is the `lt lambda_18044, qs32 3`. This means that the bisection in `SmallStack.read` has not been eliminated.

**Comment by leissa** [comment]
Works here - even with the new syntax:
```
$  impala rodent.impala -emit-thorin -Othorin 
module 'rodent'


main_9775(mem mem_9776, [pf32]* res_9777, fn(mem, ()) return_9778) extern 
    pf32* n_9781 = lea res_9777, qs32 0
    pf32* n_9785 = lea res_9777, qs32 1
    mem _9783 = store mem_9776, n_9781, pf32 0
    pf32* n_9788 = lea res_9777, qs32 2
    pf32* n_9800 = lea res_9777, qs32 5
    pf32* n_9804 = lea res_9777, qs32 6
    pf32* n_9808 = lea res_9777, qs32 7
    pf32* n_9792 = lea res_9777, qs32 3
    pf32* n_9796 = lea res_9777, qs32 4
    mem _9786 = store _9783, n_9785, pf32 0
    mem _9790 = store _9786, n_9788, pf32 42
    mem _9794 = store _9790, n_9792, pf32 126
    mem _9798 = store _9794, n_9796, pf32 252
    mem _9802 = store _9798, n_9800, pf32 420
    mem _9806 = store _9802, n_9804, pf32 630
    mem _9810 = store _9806, n_9808, pf32 882
    return_9778(_9810, tuple ())
```

**Comment by madmann91** [comment]
By the way, this new commit you added (05e40c1f9755011df16a17d397bb137ba6053535) makes the PE diverge on one variant in Rodent, even though this variant was working previously. The `divergent loop is `while (!queue.empty()) {` in `partial_evaluation.cpp`. It seems that it keeps processing continuations that come from PE (generated during mangling?).

**Comment by madmann91** [comment]
I will give it a shot again.

**Comment by leissa** [comment]
Yes, most likely - but this doesn't mean it's a bug. We should get ```pe_info``` back. It really helps debugging and understanding what's going on.

**Comment by madmann91** [comment]
I just tested it on my laptop. It seems to work there. I guess this is fixed then. I'll try to find a small example for the broken Rodent variant. It's basically the same code, so I do not get why this is no working now.

**Comment by leissa** [comment]
My last commit 66a81419b252c0fed2fddd30321bb2c8100b89d3 shouldn't effect anything, btw. It's currently not used.

**Comment by madmann91** [comment]
I have narrowed the problem down. Here is a piece of code that does not go through:

```rust
fn @batcher_sort() -> () {
    fn @sort(len: int) -> () {
        if len > 1 {
            sort(len / 2);
        }
    }

    sort(eight(1))
}

fn @eight(k: int) -> int {
    if k == 0 {
        8
    } else {
        eight(k - 1)
    }
}

fn main() -> () {
    batcher_sort();
}
```

**Comment by leissa** [comment]
Just by looking at the Code: I guess the problem is the @ for sort which ist recursive

**Comment by madmann91** [comment]
But here it works if you call `sort(8)`. And `eight(1)` evaluates to `8` when used alone. I suspect that the return continuations need to be inlined in order to specialize a function with the result of another function. Here it does not work because `eight()` is recursive.

**Comment by madmann91** [comment]
This is a bug. The `pe_profile` of `eight()` is set to `false` for some reason. Will investigate.

**Comment by leissa** [comment]
No, it's a different issue. We fold eight but don't propagate to it's return continuation.

**Comment by madmann91** [comment]
Parameter elimination is now properly propagating the profile so that is fixed.

**Comment by leissa** [comment]
ah yes :)

**Comment by leissa** [comment]
This was definitely an issue, but there was still the problem I mentioned earlier that we didn't propagate into the return continuation. 246ec003a53dc8d7251e118bf0bc5b02b6b24cb2 should fix this.

**Comment by madmann91** [comment]
The snippet with `eight` as a recursive function still does not work.

**Comment by leissa** [comment]
I'm working on it...

**Comment by leissa** [comment]
The problem is that
```
fn(a: int, ret: fn(int)) @(true, true)
    ...
```
and some call
```
f(23, k)
```
will specialize to this:
```
k(42)
```
and all continuations nested inside of ```k``` don't see ```42``` but ```k```'s parameter instead.

After, clean up this problem is gone - but this is too late. Also just checking at the call-site whether a continuation only has one user isn't enough (see 246ec00) because we might end up with dead/unreachable users of an callee.

So, in c6b084f I annotate continuations which gets specialized with an all-true profile if they only have one user. But maybe this is too aggressive?

**Comment by madmann91** [comment]
I think it is not aggressive enough ;) It does not work with non tail-recursive functions:

```rust
fn @(?i) ilog2(i: int) -> int {
    if i <= 1 {
        0
    } else {
        ilog2(i / 2) + 1
    }
}

fn @sort(len: int) -> () {
    if len > 1 {
        sort(len / 2)
    }
}

fn main() -> () {
    sort(1 << ilog2(8, 0))
}
```

**Comment by leissa** [comment]
```rust
fn foo(/*...*/) -> int { /*...*/ }

fn @bar(g: fn(/*...*/) -> int) -> int {
    //...
    let x = foo();
    //...
    let y = foo();
    //...
}

//...
bar(foo)
```

here we would specialize ```foo``` twice because at the moment we pass ```foo``` to ```bar```, ```foo``` only has one user - sth we may do not want...

**Comment by madmann91** [comment]
How about applying this only to basic blocks, not functions? After specialization, the return continuation is usually a basic block. This would take care of this case, at least, but correct me if I am wrong.

**Comment by leissa** [comment]
Ok, the log example doesn't work because the use counter may still contain dead stuff even if we count before folding.

I think the best solution is to always annotate return-continuations built in impala with an all-true profile. In thorin we don't know which continuations are there on purpose and which ones are there by accident, if you know what I mean.

**Comment by leissa** [comment]
see my last commit in impala and thorin

**Comment by madmann91** [comment]
Can't we just annotate every call to a continuation argument that happen _inside_ the folded continuation as to be inlined (with the new Run PrimOp)? I suppose your solution would imply that:

```rust
fn foo(i: int, ret: fn (int) -> !) -> !
```

does not behave like:

```rust
fn foo(i: int) -> int
 ```

**Comment by leissa** [comment]
No, I mean that
```
let x = foo(i);
```
is different from
```
foo(i, k)
```
because there might be a second call
```
bar(j, k)
```
and in this case I guess we don't want to specialize the residual call to ```k```?

Another option would be to simply look for these things beforehand, count the uses and set an all-true profile. Then, do the PE.

Sorry, I don't get your suggestion. Can you elaborate a bit more?

**Comment by madmann91** [comment]
Well, the problem with your previous approach is that it relied on the number of uses to perform inlining. Disregarding the fact that this number is incorrect, this might be too aggressive as you pointed out. In our case, we are just interested at the uses happening at one particular call site, not _every_ use.
Say we have a continuation `f`, on which we are trying to perform PE:

```
f(..., ret: fn (int)):
  ...

  g(...):
    ret(...)
```

At the call site, we have something like:

```
call_to_f(...):
  f(..., f_cont)

f_cont(i: int):
  ...
```

We only want to eat calls to the continuation `f_cont` that will happen _inside_ the specialized continuation generated from dropping the call to `f`. Some other use of `f_cont` should be kept intact. In this example, we want to get a rid of the call to `f_cont` in `dropped_g`:

```
call_to_f(...):
  ...

dropped_g(...):
  f_cont(...)

f_cont(i: int):
  ...
```

**Comment by madmann91** [comment]
This transformation should be safe when `f_cont` is a basic block.

**Comment by leissa** [comment]
But even *inside* f we can have multiple ret calls which might end up in multiple residual calls. And in this case we don't want to inline, right?
```
f(..., ret: fn(int))
    br(..., T, F)
T()
    ret(23)
F()
    ret(42)
```
Now, suppose we have
```
cur(...)
    f(..., k)
```
and after dropping:
```
cur(...)
    f'()
f'()
    br(..., T', F')
T'()
    k(23)
F'()
    k(42)
```
Now, specializing those k-calls might be a bad idea.

**Comment by madmann91** [comment]
I think it is fine if you do this only when `k` is of order 1 (a basic block). After all, the return continuation is here as an administrative term: It only says where to jump. By inlining it, we are merely performing the jump.

**Comment by leissa** [comment]
But in my example above, we would double the whole program. One with 23, one with 42.

**Comment by leissa** [comment]
The precise way would be actually to let the programmer decide whether he wants the ret-call to specialize or not - maybe using certain conditions...

**Comment by madmann91** [comment]
I see your point. Maybe we should do that when `f_cont` is a simple block (only passing arguments through)?

**Comment by leissa** [comment]
So, this super recursive thing, we talked about didn't work out as expected. It is doable but requires more work, as we encountered a couple of problems. However, I implemented another trick in 83c517d93f0372f44559d0258fa2ad14df9dd52d and removed the workaround in AnyDSL/impala@ce4a48da393b4eadc472a534479a66beab4a9db7. So far, it seems like this works :)

**Comment by leissa** [comment]
The trick in 83c517d still isn't enough. My last commit is super bruteforce and slow but works for now. This recursive stuff should work - once we have the implementation correct - but I'll return to it after vacation.

**Comment by leissa** [comment]
Can you give the ```pe_fix_point``` (impala + thorin) branch a try? Now, I solved this issue, by letting the PE run in the fix-point loop.

**Comment by leissa** [comment]
pe_fix_point works now
